### ISSUE TITLE
Enable this repo on Travis

### ISSUE THREAD

**Issue by DavidePastore** [italia/design-react#6]
Two things to do:

- enable this repo on [Travis](https://travis-ci.org/italia/design-react);
- edit the related url on README.md.

**Comment by ruphy** [comment]
Enabled, thanks!
Can I close this as fixed?
you can send a PR for the README if you wish, so you get the credits :)

**Comment by DavidePastore** [comment]
@ruphy thanks! However `npm install` is failing 😮

**Comment by ruphy** [comment]
yes, I have really no idea about why o.o

**Comment by DavidePastore** [comment]
This should be fixed in #8.

**Comment by DavidePastore** [comment]
@ruphy This still causes issues 🗡 Take a look to the [build result](https://travis-ci.org/italia/design-react). I think somebody should [setup Travis to deploy to github pages branch](https://docs.travis-ci.com/user/deployment/pages/). 😸

**Comment by dej611** [comment]
I suspect the fact that 2 builds are made is also problematic. The `gh-pages` depoyment should happen only for one version of Node.

**Comment by ruphy** [comment]
fixed! <3
